# Generated by Django 4.1.3 on 2022-11-08 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="unit_price",
            new_name="price",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
