# Generated by Django 4.0 on 2022-12-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='id',
            new_name='_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='store.Promotion'),
        ),
    ]
