databases:
  - name: ecom_app
    databaseName: ecom_app
    user: ecom_app

services:
  - type: web
    name: ecom_app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ecom_app.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecom_app
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4